bfrs/urls.py
# from django.conf.urls import include, url
from django.urls import include, path, re_path
from bfrs.models import Bushfire
from bfrs import views

app_name = 'bfrs'

# urlpatterns = [
#     url(r'^create/$', views.BushfireUpdateView.as_view(), name='bushfire_create'),
#     url(r'^initial/(?P<pk>\d+)/$', views.BushfireUpdateView.as_view(), name='bushfire_initial'),
#     url(r'^initial/snapshot/(?P<pk>\d+)/$', views.BushfireInitialSnapshotView.as_view(), name='initial_snapshot'),
#     url(r'^final/(?P<pk>\d+)/$', views.BushfireUpdateView.as_view(), name='bushfire_final'),
#     url(r'^final/snapshot/(?P<pk>\d+)/$', views.BushfireFinalSnapshotView.as_view(), name='final_snapshot'),
# #    url(r'^export/$', views.BushfireView.as_view(), name='export'),

#     url(r'^history/(?P<pk>\d+)/$', views.BushfireHistoryCompareView.as_view(), name='bushfire_history'),
#     url(r'report/$', views.ReportView.as_view(), name='bushfire_report'),
#     url(r'^bushfire/(?P<bushfireid>\d+)/document/$', views.BushfireDocumentListView.as_view(), name='bushfire_document_list'),
#     url(r'^bushfire/(?P<bushfireid>\d+)/document/upload/$', views.BushfireDocumentUploadView.as_view(), name='bushfire_document_upload'),
#     url(r'^document/(?P<pk>\d+)/download/$', views.DocumentDownloadView.as_view(), name='document_download'),
#     url(r'^document/(?P<pk>\d+)$', views.DocumentUpdateView.as_view(), name='document_update'),
#     url(r'^document/(?P<pk>\d+)/edit/$', views.DocumentUpdateView.as_view(), name='document_edit'),
#     url(r'^document/(?P<pk>\d+)/view/$', views.DocumentDetailView.as_view(), name='document_view'),
#     url(r'^document/(?P<pk>\d+)/delete/$', views.DocumentDeleteView.as_view(), name='document_delete'),
#     url(r'^document/(?P<pk>\d+)/archive/$', views.DocumentArchiveView.as_view(), name='document_archive'),
#     url(r'^document/(?P<pk>\d+)/unarchive/$', views.DocumentUnarchiveView.as_view(), name='document_unarchive'),
#     url(r'^documentcategory/$', views.DocumentCategoryListView.as_view(), name='documentcategory_list'),
#     url(r'^documentcategory/create/$', views.DocumentCategoryCreateView.as_view(), name='documentcategory_create'),
#     url(r'^documentcategory/(?P<pk>\d+)/$', views.DocumentCategoryUpdateView.as_view(), name='documentcategory_update'),
#     url(r'^documentcategory/(?P<pk>\d+)/detail/$', views.DocumentCategoryDetailView.as_view(), name='documentcategory_detail')

# ]
urlpatterns = [
    path('create/', views.BushfireUpdateView.as_view(), name='bushfire_create'),
    path('initial/<int:pk>/', views.BushfireUpdateView.as_view(), name='bushfire_initial'),
    path('initial/snapshot/<int:pk>/', views.BushfireInitialSnapshotView.as_view(), name='initial_snapshot'),
    path('final/<int:pk>/', views.BushfireUpdateView.as_view(), name='bushfire_final'),
    path('final/snapshot/<int:pk>/', views.BushfireFinalSnapshotView.as_view(), name='final_snapshot'),
    # path('export/', views.BushfireView.as_view(), name='export'),

    path('history/<int:pk>/', views.BushfireHistoryCompareView.as_view(), name='bushfire_history'),
    path('report/', views.ReportView.as_view(), name='bushfire_report'),
    path('bushfire/<int:bushfireid>/document/', views.BushfireDocumentListView.as_view(), name='bushfire_document_list'),
    path('bushfire/<int:bushfireid>/document/upload/', views.BushfireDocumentUploadView.as_view(), name='bushfire_document_upload'),
    path('document/<int:pk>/download/', views.DocumentDownloadView.as_view(), name='document_download'),
    path('document/<int:pk>/', views.DocumentUpdateView.as_view(), name='document_update'),
    path('document/<int:pk>/edit/', views.DocumentUpdateView.as_view(), name='document_edit'),
    path('document/<int:pk>/view/', views.DocumentDetailView.as_view(), name='document_view'),
    path('document/<int:pk>/delete/', views.DocumentDeleteView.as_view(), name='document_delete'),
    path('document/<int:pk>/archive/', views.DocumentArchiveView.as_view(), name='document_archive'),
    path('document/<int:pk>/unarchive/', views.DocumentUnarchiveView.as_view(), name='document_unarchive'),
    path('documentcategory/', views.DocumentCategoryListView.as_view(), name='documentcategory_list'),
    path('documentcategory/create/', views.DocumentCategoryCreateView.as_view(), name='documentcategory_create'),
    path('documentcategory/<int:pk>/', views.DocumentCategoryUpdateView.as_view(), name='documentcategory_update'),
    path('documentcategory/<int:pk>/detail/', views.DocumentCategoryDetailView.as_view(), name='documentcategory_detail')
]


bfrs_api_wrapper/urls.py
from django.contrib import admin
from django.urls import path, re_path
from bfrs_api_wrapper import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/dfes/incident', api.create_dfes_incident)
]

bfrs_project/urls.py
# from django.conf.urls import url
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.contrib import admin
from bfrs import views
from bfrs.api import v1_api

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.conf import settings

from .views import ChainedModelChoicesView

from .signals import webserver_ready
from django_media_serv.urls import urlpatterns as media_serv_patterns

def sss_selection_view(request):
    return HttpResponseRedirect(settings.SSS_URL)


def home_view_selection_view(request):
    # if request.user.is_authenticated():
    if request.user.is_authenticated:
        return redirect('main')
    else:
        return redirect('login')


def admin_view_selection_view(request):
    if request.user.is_superuser:
        return admin.site.index(request)
    elif request.user.is_authenticated():
        return redirect('main')
    else:
        return redirect('login')


urlpatterns = [
    # Authentication URLs
    # url(r'^', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    #url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name='logout'),
    # url(r'^main/$', login_required(views.BushfireView.as_view()), name='main'),
    path('main/', login_required(views.BushfireView.as_view()), name='main'),
    # url(r'^admin/$', admin_view_selection_view),
    path('admin/', admin_view_selection_view),
    #url(r'^bfrs/', include('bfrs.urls', namespace='bushfire')),
    # url(r'^bfrs/', include(('bfrs.urls', 'bfrs'), namespace='bushfire')),
    path('bfrs/', include(('bfrs.urls', 'bfrs'), namespace='bushfire')),
    #url(r'^admin/', include(admin.site.urls)),
    path('admin/', admin.site.urls),
    # url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^api/', include(v1_api.urls)),
    # url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    # url(r'^sss/$', sss_selection_view, name="sss_home"),
    # url(r'^chaining/', include('smart_selects.urls')),
    # url(r'^options/js/(?P<chained_model_app>[a-zA-Z0-9\_\-]+)/(?P<chained_model_name>[a-zA-Z0-9\_\-]+)/(?P<model_app>[a-zA-Z0-9\_\-]+)/(?P<model_name>[a-zA-Z0-9\_\-]+)', ChainedModelChoicesView.as_view(),name="chained_model_choices"),
    # url(r'^$', home_view_selection_view, name='home'),
    # path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('api/', include(v1_api.urls)),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('sss/', sss_selection_view, name="sss_home"),
    path('chaining/', include('smart_selects.urls')),
    re_path(r'^options/js/(?P<chained_model_app>[a-zA-Z0-9\_\-]+)/(?P<chained_model_name>[a-zA-Z0-9\_\-]+)/(?P<model_app>[a-zA-Z0-9\_\-]+)/(?P<model_name>[a-zA-Z0-9\_\-]+)', ChainedModelChoicesView.as_view(), name="chained_model_choices"),
    path('', home_view_selection_view, name='home'),
] + media_serv_patterns

webserver_ready.send(sender="urls")

bfrs/templates/bfrs/bushfire_document_create.html
{% extends "admin/base_site.html" %}
{% load static from static %}
{% load bfrs_tags %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.css' %}"/ >
{% endblock %}

{% block extra_js %}
  {{ block.super }}
  {% for field in form %}
    {{ field.media }}
  {% endfor %}
  <script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
  {{ form.media }}
  

{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'main' %}">Bushfire Overview</a></li>
  <li><a href="{{bushfireurl}}">{% if bushfire.report_status == bushfire.STATUS_INVALIDATED %} 
        <font color="red">{{ bushfire.fire_number}} (Invalid)</font>
      {% elif bushfire.report_status == bushfire.STATUS_MERGED %} 
        <font color="red">{{ bushfire.fire_number}} (Merged)</font>
      {% elif bushfire.report_status == bushfire.STATUS_DUPLICATED %} 
        <font color="red">{{ bushfire.fire_number}} (Duplicated)</font>
      {% else %}
        {{ bushfire.fire_number }}
      {% endif %}
  </a></li>
  <li><a href="{% url 'bushfire:bushfire_document_list' bushfireid=bushfire.id %}">Documents</a></li>
  <li>Add document</li>
</ul>
{% endblock %}

{% block content %}
<table style="width:100%">
<tr>
    <td style="padding-left:0px">
      <h1 style="float:left">Upload Bushfire Document</h1>
    </td>
</tr>
</table>

{% if form.errors %}
    <h1 class="errornote">
      <p>Form Errors</p>
      <button type="button" class="close" data-dismiss="alert">×</button>
      <ul>
      {% for field in form %} 
          {% if field.errors %}
          <li>{{ field.label }}: {{ field.errors|striptags }}</li>
          {{ field.meta  }}
          {% endif %}
      {% endfor %}

      {% if form.non_field_errors %}
          <li>{{ form.non_field_errors  }}</li>
      {% endif %}
      </ul>
    </h1>
{% endif %}


<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<table class="table table-bordered table-striped table-condensed">
<tr>
    <th class="cbas" >Category*</th>
    <td class="cbas" >{{form.category}}</td>
</tr>
<tr>
    <th class="cbas" >Descriptor*</th>
    <td class="cbas" >{{form.tag}}</td>
</tr>
<tr>
    <th class="cbas" >Document*</th>
    <td class="cbas" >{{form.document}}</td>
</tr>
<tr>
    <th class="cbas" >Document created</th>
    <td class="cbas" >{{form.document_created}}</td>
</tr>
</table>
<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
        <p class="pull-right">
            <button type="submit" class="btn btn-primary btn-success"  name="action" value="create"/>Upload </button>
            <button type="button" class="btn btn-primary btn-danger"  onclick="window.location='{% url "bushfire:bushfire_document_list"  bushfireid=bushfire.id %}'">Cancel </button>
      </p>
    </div>
  </div>
</div>
</form>
{% endblock %}

bfrs/templates/bfrs/bushfire_document_list.html
{% extends "admin/base_site.html" %}
{% load static from static %}
{% load bfrs_tags %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'main' %}">Bushfire Overview</a></li>
  <li><a href="{{bushfireurl}}">{% if bushfire.report_status == bushfire.STATUS_INVALIDATED %} 
        <font color="red">{{ bushfire.fire_number}} (Invalid)</font>
      {% elif bushfire.report_status == bushfire.STATUS_MERGED %} 
        <font color="red">{{ bushfire.fire_number}} (Merged)</font>
      {% elif bushfire.report_status == bushfire.STATUS_DUPLICATED %} 
        <font color="red">{{ bushfire.fire_number}} (Duplicated)</font>
      {% else %}
        {{ bushfire.fire_number }}
      {% endif %}
  </a></li>
  {% if snapshot %}
  <li>snapshot</li>
  {% endif %}
  <li>Documents</li>
</ul>
{% endblock %}

{% block content %}
<table style="width:100%">
<tr>
    <td style="padding-left:0px">
      <h1 style="float:left">Bushfire Documents</h1>
    </td>

</tr>
</table>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" style="margin-bottom:10px">
  <div class="panel-primary">
    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#filter" aria-expanded="true" aria-controls="filter"><button><i class="icon-filter icon-white"></i> Filter tools</button></a>
    <button class="btn btn-primary btn-info" type="button" style="float:right;margin-right:15px" onclick="window.location='{% url "bushfire:bushfire_document_upload"  bushfireid=bushfire.id %}'"><i class="icon-upload-alt"></i> Add Document</button>
    <div id="filter" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="pn_filter">
      <div class="panel-body">
        <!--<form action="" method="get">-->
        <form id="bushfire_document_filter" action="" method="get">
          <table class="table table-bordered table-striped table-condensed" style="margin-bottom:0px;">
            <body>
              <tr>
                <td class="cbas" style="padding:20px;">
                  <div class="filter-controls-container" style="display: flex; flex-wrap: wrap; align-items: flex-end; gap: 20px;">
                    <div class="filter-item" style="display: flex; flex-direction: column;">
                      <label class="nowrap">Category</label> <!-- Removed inline font-weight and margin-bottom -->
                      <div class="controls ">{{ filterform.category }}</div>
                    </div>

                    <div class="filter-item" style="display: flex; flex-direction: column;">
                      <label class="nowrap">Archived</label> <!-- Removed inline font-weight and margin-bottom -->
                      <div class="controls ">{{ filterform.archived }}</div>
                    </div>

                    <div class="filter-item" style="display: flex; flex-direction: column;">
                      <label class="nowrap">Last modified</label> <!-- Removed inline font-weight and margin-bottom -->
                      <div class="controls ">{{ filterform.last_modified }}</div>
                    </div>

                    <div class="filter-item filter-search" style="display: flex; flex-direction: column; flex-grow: 1; min-width: 200px;">
                      <label class="nowrap">Search Tag,Custom Tag and Creator</label> <!-- Removed inline font-weight and margin-bottom -->
                      <div class="controls ">{{ filterform.search }}</div>
                    </div>

                    <div class="filter-item filter-button" style="align-self: flex-end; margin-bottom: 4px;">
                      <button type="submit"><i class="icon-refresh icon-white"></i> Update</button>
                    </div>
                  </div>
                </td>
              </tr>
            </body>
          </table>
        </form>
      </div>
    </div>
  </div>
</div>

<script>

</script>
<table id="table" class="table table-striped table-bordered table-hover table-condensed" style="cursor:pointer;">
  <thead>
     <th onclick="document.location='{{filters_without_order}}{{'document_tag'|toggle_sort:filter.data}}'" class="headerSort {{'document_tag'|sort_class:filter.data}}">
       <font color="dodgerblue">Descriptor</font>
     </th>
     <th onclick="document.location='{{filters_without_order}}{{'category'|toggle_sort:filter.data}}'" class="headerSort {{'category'|sort_class:filter.data}}">
       <font color="dodgerblue">Category</font>
     </th>
     <th onclick="document.location='{{filters_without_order}}{{'document_created'|toggle_sort:filter.data}}'" class="headerSort {{'document_created'|sort_class:filter.data}}">
       <font color="dodgerblue">Created on</font>
     </th>
     <th onclick="document.location='{{filters_without_order}}{{'archived'|toggle_sort:filter.data}}'" class="headerSort {{'archived'|sort_class:filter.data}}">
       <font color="dodgerblue">Archived?</font>
     </th>
     <th onclick="document.location='{{filters_without_order}}{{'creator'|toggle_sort:filter.data}}'" class="headerSort {{'creator'|sort_class:filter.data}}">
       <font color="dodgerblue">Uploaded By</font>
     </th>
     <th onclick="document.location='{{filters_without_order}}{{'created'|toggle_sort:filter.data}}'" class="headerSort {{'created'|sort_class:filter.data}}">
       <font color="dodgerblue">Uploaded on</font>
     </th>
    <th ></th>
  </thead>
  <tbody>
    {% for doc in object_list %}
      <tr class="row-vm" data-toggle="myCollapse" data-target="#{{bushfire.id}}">
          <td>{{doc.document_tag}}</td>
          <td>
              {{doc.category}}
          </td>
          <td>{{doc.document_created}}</td>
          <td>{% if doc.archived %} 
              Yes
              {% else %} 
              No
              {% endif %}
          </td>
          <td>{{doc.creator}}</td>
          <td>{{doc.created | date:"Y-m-d H:i:s"}}</td>
          <td>
              {% if not doc.archived %}
              <a style="margin-left:10px" href="{% url "bushfire:document_edit" doc.id %}" title="Edit Document"><i class="icon-edit"></i></a>
              <a style="margin-left:10px" href="{% url "bushfire:document_archive" doc.id %}" title="Archive Document"><i class="icon-folder-close"></i></a>
              {% else %}
              <a style="margin-left:10px" href="{% url "bushfire:document_view" doc.id %}" title="View Document"><i class="icon-eye-open"></i></a>
              <a style="margin-left:10px" href="{% url "bushfire:document_unarchive" doc.id %}" title="Unarchive Document"><i class="icon-folder-open"></i></a>
              {% endif %}
              <a style="margin-left:10px" href="{% url "bushfire:document_download" doc.id  %}" title="Download Document"><i class="icon-download-alt"></i></a>
              <a style="margin-left:10px" href="{% url "bushfire:document_delete" doc.id %}" title="Delete Document"><i class="icon-trash"></i></a>
          </td>
      </tr>
    {% empty %}
      <tr>
          <td colspan="7" style="text-align:center">There are no attached documents</td>
      </tr>
    {% endfor %}
  </tbody>
</table>


<!-- js bushfire_filter() function used below to allow pagination to work with the filters (filter params are combined in the fucntions)-->
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <!--li><a href="javascript: bushfire_filter({page:{{ page_obj.previous_page_number }}});">&laquo;</a></li-->
      <li><a href="{{filters}}page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <!--li><a href="javascript: bushfire_filter({page:{{ i }}});">{{ i }}</a></li-->
        <li><a href="{{filters}}page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <!--li><a href="javascript: bushfire_filter({page:{{ page_obj.next_page_number }}});">&raquo;</a></li-->
      <li><a href="{{filters}}page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

</script>
{% endblock %}

bfrs/templates/bfrs/documentcategory_list.html
{% extends "admin/base_site.html" %}
{% load static from static %}
{% load bfrs_tags %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'main' %}">Bushfire Overview</a></li>
  <li>Document Categories</li>
</ul>
{% endblock %}

{% block content %}
<table style="width:100%"><tr>
<td style="padding-left:0px">
  <h1 style="float:left">Document Categories</h1>
</td>
{% if can_maintain_data %}
<td style="vertical-align:bottom;padding-right:0px">
  <span style="float:right">
      <button class="btn btn-primary btn-success" type="button" onclick="window.location='{% url "bushfire:documentcategory_create" %}'"> Add Document Category</button>
  </span>
</td>
{% endif %}
</tr></table>

<table id="table" class="tablesorter table table-striped table-bordered table-hover table-condensed" style="cursor:pointer;">
  <thead>
    <th >Name </th>
    <th >Archived? </th>
    <th >creator </th>
    <th >created </th>
    <th ></th>
  </thead>
  <tbody>
    {% for category in object_list %}
      <tr class="row-vm" >
          <td>{{category.name}}</td>
          <td>{{category.archived|yesno:"Yes,No"}}</td>
          <td>{{category.creator}}</td>
          <td>{{category.created}}</td>
          <td>
            <a style="margin-left:10px" href="{% url "bushfire:documentcategory_detail" category.id %}" title="View Document Category"><i class="icon-eye-open"></i></a>
            {% if can_maintain_data  %}
              <a style="margin-left:10px" href="{% url "bushfire:documentcategory_update" category.id %}" title="Edit Document Category"><i class="icon-edit"></i></a>
            {% endif %}
          </td>
      </tr>
    {% empty %}
      <tr class="row-vm">
          <td colspan="5" style="text-align:center">There are no document categories.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

bfrs/templates/bfrs/mandatory_fields.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load static %}
{% load bfrs_tags %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'main' %}">{% trans 'Bushfire Overview' %}</a> <span class="divider"></span></li>
  {% if object.report_status == object.STATUS_INITIAL %}
    <li><a href="{% url 'bushfire:bushfire_initial' object.id %}">{{object.fire_number}}</a> <span class="divider"></span></li>
  {% else  %}
    <li><a href="{% url 'bushfire:bushfire_final' object.id %}">{{object.fire_number}}</a> <span class="divider"></span></li>
  {% endif %}
  <li>Field errors</li>
</ul>
{% endblock %}

{% block content_title %}
    <h1>The following mandatory fields are missing. Cannot perform action '{{action|split_capitalize}}' until complete.</h1>
{% endblock %}

{% block content %}

    {% if mandatory_fields %}
      <ol>
        {% for field in mandatory_fields %}
          <li>{{field|split_capitalize}}</li>
        {% endfor %}
      </ol>
    {% endif %}
    <div>
        <a id="id_ok_btn" {% if object.report_status == object.STATUS_INITIAL %} href="{% url 'bushfire:bushfire_initial' object.id %}" {% else %} href="{% url 'bushfire:bushfire_final' object.id %}"{% endif %} class="btn btn-info">Return</a>
    </div>
{% endblock %}


bfrs/templates/bfrs/snapshot_history.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load static %}
{% load bfrs_tags %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'main' %}">{% trans 'Bushfire Overview' %}</a> <span class="divider"></span></li>
  {% if object.report_status >= Bushfire.STATUS_INITIAL_SUBMITTED %}
    <li><a href="{% url 'bushfire:bushfire_final' object.id %}">{{object.fire_number}}</a> <span class="divider"></span></li>
  {% endif %}
  <li>Snapshot History</li>
</ul>
{% endblock %}

{% block content_title %}
    <h1>Snapshot change history - {{object.fire_number}}</h1>
{% endblock %}

{% block content %}


{% if object.report_status >= Bushfire.STATUS_INITIAL_SUBMITTED %}
<p>Click on row to expand/collapse the change details</p>
<table id="table" class="tablesorter table table-striped table-bordered table-hover table-condensed">
  <thead>
	  <th></th>
	  <th>Action</th>
	  <th>Modified</th>
	  <th>Modifier</th>
  </thead>
  <tbody>
      {% comment %}{% for snapshot in object.snapshot_history.all %}{% endcomment %}
    {% for snapshot in object.snapshot_list %}
      <tr class="row-vm" data-toggle="myCollapse" data-target="#{{snapshot.id}}">
        <td>{{ forloop.counter  }}</td>
        <td>{{ snapshot.action|split_capitalize }}</td>
        <td>{{ snapshot.modified|date:'Y-m-d H:i' }}</td>
        <td>{{ snapshot.modifier }}</td>
      </tr>

      <tr class="myCollapse row-details expand-child" id="{{snapshot.id}}">
        <td colspan="4">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <th></th>
              <th>Field Name</th>
              <th>New Value</th>
              <th>Old Value</th>
            </thead>

            <tbody>
              {% for key, values in snapshot.diff.items %}
              <tr>
                <td>{{ forloop.counter  }}</td>
                <td>{{ key }}</td>
                <td>{{ values.0 }}</td>
                <td>{{ values.1 }}</td>
              </tr>
              {% empty %}
                {%  if snapshot.action|split_capitalize not in "Submit,Authorise,Delete Final Authorisation,Delete Reviewed"|slice:"," %}
                  <td colspan="4">Changes are not available (most likely Damages/Injuries/Tenures changed)</td>
                {% else %}
                  <td colspan="4">Changes are not available for this Action</td>
                {% endif %}
              {% endfor %}
            </tbody>
          </table>
        </td>
      </tr>

    {% endfor %}
  </tbody>
</table>


{% else %}
  <p>Initial Report has not yet been 'Submitted'</p>
{% endif %}
{% if object.report_status >= object.STATUS_INITIAL_AUTHORISED %}
  <a id="id_ok_btn" href="{% url 'bushfire:bushfire_final' object.id %}" class="btn btn-info">Bushfire Details</a>
{% else %}
  <a id="id_ok_btn" href="{% url 'bushfire:bushfire_initial' object.id %}" class="btn btn-info">Bushfire Details</a>
{% endif %}
<a id="id_cancel_btn" href="{% main_url %}" class="btn btn-info">Return</a>

<script>

    $("[data-toggle=myCollapse]").click(function( ev ) {
      ev.preventDefault();
      var target;
      if (this.hasAttribute('data-target')) {
    target = $(this.getAttribute('data-target'));
      } else {
    target = $(this.getAttribute('href'));
      };
      target.toggleClass("in");
    });

    $("#table td a").on('click', function (e) { e.stopPropagation(); })

</script>
{% endblock %}
